### ISSUE TITLE
Formatting issues

### ISSUE THREAD

**Issue by joedixon** [Stillat/blade-parser-typescript#63] opened 2023-06-21 12:11 UTC
Hey @JohnathonKoster 👋

First of all, loving your work on this plugin, it's very cool to see how much progress you're making.

Just wanted to highlight a couple of minor issues I've run into. The first is related to conditional includes which you can see below:

<img width="554" alt="Screenshot 2023-06-21 at 13 05 01" src="https://github.com/Stillat/blade-parser-typescript/assets/3438564/3f708dc0-96a4-4ddb-96a8-efa7932e72bd">

Second, an issue with escaping blade tags for use with Javascript.

<img width="432" alt="Screenshot 2023-06-21 at 12 03 48" src="https://github.com/Stillat/blade-parser-typescript/assets/3438564/c16c9cf4-2f5b-4b42-9e70-cf924ef1a790">

If there is any further info I can provide to help here, please let me know.

**Comment by JohnathonKoster** [comment] 2023-06-21 14:43
Thanks for the report! I'll look into both of these (the escaped one might be challenging since I'm not guaranteed to always have the `}}` closing sequence when we start escaped content).

For the conditional include, is the screenshot the before or after results?

Thank you!

**Comment by joedixon** [comment] 2023-06-22 11:56
Yeah, that does sound tricky. I guess in most cases you would expect a closing `}}`, but definitely can't rely on it.

Here's the full diff of the conditional includes:

![Screenshot 2023-06-21 at 12 02 59](https://github.com/Stillat/blade-parser-typescript/assets/3438564/88dc1cc5-f30b-4fc1-a693-f3e8365ed9e5)

**Comment by JohnathonKoster** [comment] 2023-06-22 22:57
Would you be able to provide your `package.json`, the original (or comparable) file that is experiencing issues, as well as the prettier configuration?

I have been unable to reproduce, and having that information helps immensely.

**Comment by joedixon** [comment] 2023-06-27 08:29
Sure, here is the package.json

```json
{
  "private": true,
  "scripts": {
    "dev": "npm run development",
    "development": "mix",
    "watch": "mix watch",
    "watch-poll": "mix watch -- --watch-options-poll=1000",
    "hot": "mix watch --hot",
    "production": "mix --production",
    "prod": "npm run production"
  },
  "devDependencies": {
    "@fullhuman/postcss-purgecss": "^5.0",
    "axios": "^1.0",
    "bootstrap": "^5.0",
    "brace": "^0.11.0",
    "cross-env": "^5.1",
    "jquery": "^3.7.0",
    "laravel-echo": "^1.8.1",
    "laravel-mix": "^6.0.49",
    "lodash": "^4.17.19",
    "moment": "^2.27",
    "@popperjs/core": "^2.11.8",
    "postcss": "^8.3.1",
    "pusher-js": "^4.4.0",
    "resolve-url-loader": "^5.0.0",
    "sass": "^1.63.4",
    "sass-loader": "^12.1.0",
    "sortablejs": "^1.4.2",
    "tailwindcss": "^1.9.6",
    "vue": "^2.7.14",
    "vue-loader": "^15.9.8",
    "vue-template-compiler": "^2.7.14"
  },
  "dependencies": {
    "mousetrap": "^1.6.5",
    "vuedraggable": "^2.24.1"
  }
}
```

And the prettier config is the default from the readme:

```json
{
    "plugins": [
        "./node_modules/prettier-plugin-blade/"
    ],
    "overrides": [
        {
            "files": [
                "*.blade.php"
            ],
            "options": {
                "parser": "blade"
            }
        }
    ]
}
```

**Comment by JohnathonKoster** [comment] 2023-06-27 09:37
The `.prettierrc` file looks okay, but I don't see `prettier-plugin-blade` within the `package.json` contents. Has the package been installed within the project, and available within `node_modules`?

```bash
npm install prettier-plugin-blade
```

**Comment by joedixon** [comment] 2023-06-27 12:50
My bad - I had it installed when I ran into the formatting issues, but removed it temporarily while we discuss the issue.

**Comment by JohnathonKoster** [comment] 2023-06-27 18:22
That's fair! Would you be able to supply the full Blade template as an attachment (to help preserve the original whitespace/etc.)? I'm having a lot of difficulty reproducing the issue at this time.

**Comment by joedixon** [comment] 2023-06-28 13:27
Not sure I can provide that, but did some more digging and got a minimal repro for you. Afraid to say it's linked to escaping characters...

```
<div>
    <h1>@{{ user.name }}</h1>

    <div>@if($user->avatar) @include('users.avatar')@endif</div>
</div>
```

**Comment by JohnathonKoster** [comment] 2023-06-28 14:26
I appreciate taking the effort to find a minimal repro. Unfortunately, I still cannot reproduce the issue:


https://github.com/Stillat/blade-parser-typescript/assets/5232890/6dd6b48d-b9df-4f97-81f9-153ade676ccd

**Comment by joedixon** [comment] 2023-06-28 14:54
There is no indentation of the the `@if` directive. It shows with the simple repro, but the issue is highlighted if I make the conditionals more complex as per my original post.


https://github.com/Stillat/blade-parser-typescript/assets/3438564/e1b25514-91df-4470-bc45-def426f464f4


https://github.com/Stillat/blade-parser-typescript/assets/3438564/91c38f19-9425-497e-a2bd-6f1dcafcd9c0

**Comment by JohnathonKoster** [comment] 2023-06-28 15:18
Thanks for the video! I had added some whitespace while transcribing/testing earlier. Can reproduce now.

Apologize for all the back and forth!

**Comment by joedixon** [comment] 2023-06-28 15:29
Gotcha, no problem. Lmk if there is anything I can do to help.

**Comment by JohnathonKoster** [comment] 2023-06-28 17:05
The issue with the escaped content causing unexpected results has been addressed in `1.6.6`. Thank you for all your patience and help!

**Closed by JohnathonKoster** 2023-06-28 17:05 UTC
Labels: needs more info

**Comment by joedixon** [comment] 2023-06-28 19:32
Amazing, thank you!

**Comment by joedixon** [comment] 2023-06-29 08:21
Can confirm this is working great!
